name: Docker CI/CD 

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
         
    - name: docker build image in github actions
      run: |
        docker build -t hello-docker . 
        
    - name: docker run to create container in github actions
      run: |
       docker run -d -p 80:80 hello-docker 
       
     
