name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
         
    - name: docker build nodejs
      run: |
        docker build ./nodejs -t ./nodejs:1.0.0     
    - name: docker push
      run: |
       docker push ./nodejs:1.0.0   
       
     
