name: Docker CI/CD 

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
        DOCKER_USER: ${{ secrets.DOCKER_USER}}
        
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
    steps:
    
    - uses: actions/checkout@v2
         
    - name: docker build image in github actions
      run: |
        docker build -t mylocalimage . 
        
    - name: docker run to create container in github actions
      run: |
       docker run -d -p 80:80 mylocalimage 
    
    - name: docker login    
      run: |
       docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
       
    - name: docker push to docker hub
      run: |
       docker tag mylocalimage:latest nalapatt123/github-actions:myfirstimagepush
       docker push nalapatt123/github-actions:myfirstimagepush 
        
       
       
     
