name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    - name: Docker Login
      env:
        DOCKER_USER = ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD = ${{ secrets.DOCKER_PASSWORD }}       
      run: |
       docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build nodejs
      run: |
       docker build ./nodejs -t ./nodejs:1.0.0
     
